### PR TITLE
[IMP] Refactoring Methods & Migrating to new API 

### PR DESCRIPTION
**Pull request by hbto**
Getting rid of Pylint & Flake errors,
Lowering McCabe rate on Module to acceptable rate,
Increasing Coverage of Code,
Improving code by means of creating new methods (consequence of McCabe)
using same business logic,
Making use of Abstract Class to reuse common fields structure among 
`afr` and `wizard.report` models.

Before applying this refactoring UnitTest were written, as should be,
then refactoring was performed, _No_UnitTests_were_harmed_during_this_process_
- [x] One Columns BS
- [x] One Columns IS
- [x] Two Columns BS
- [x] Two Columns IS
- [x] Four Columns BS
- [x] Four Columns IS
- [x] Five Columns BS
- [x] Five Columns IS
- [x] QTR's Columns BS
- [x] QTR's Columns IS
- [x] Twelve Columns BS
- [x] Twelve Columns IS
- [x] Testing Journal Ledger
- [x] Testing Partner Ledger
- [x] Testing Analytic Ledger
- [x] All Accounts,
- [x] With Movements,
- [x] With Balance,
- [x] With Movements or Balance,
- [x] All Entries
- [x] All Posted Entries

Only Test Missing: A.L with Analytic Lines,
though I am confident It  will work

### CODE REVIEW

**Comment by hbto** [comment]
@nhomar & @moylop260 

Your comments will be greatly appreciated 

Regards

**Comment by moylop260** [comment]
I too hard to review it because have many changes but I see the results:
+2.0% of coverage
+docstring
0 lints
-mccabe rate
+More methods inherited
+Reuse of code

Then is 👍 to avoid add more changes here

**Comment by nhomar** [comment]
:+1: 

I read carefully the changes and it looks like what moy sayss, no change of logic just coverage increased, then +1 for me.

I prefer this kind of changes rebased in only 1 commit due to is very clear the change:

_colums changeds to attributes to comply to new api and maccbe dow.. I do not see to much sense have dozebns of commits in the middle.

**Comment by nhomar** [comment]
One important comment:

**Comment by nhomar** [comment]
@hbto great job:

Some points:
1. Recommend when merge only one commit or less commits if you think is possible.
2. Take care of this

**Comment by hbto** [comment]
@nhomar 

I am fully aware of that:


That `if`statement is a consequence of the refactoring, and as you comment:
- either there is a missing test
- or actually not needed,

I lean towards there is a missing test,
But as I said previously,

_no_UnitTests_were_harmed_during_this_refactory_

Regards

**Comment by nhomar** [comment]
OK, but the coverage on this file comes down, then as you changed (because the refactor) a little bit the logic (which is ok for me) I think it is good if you add the test case just to be sure any var missing or something wear comes in. By experience when we refactor using return early strategy variables goes ugly set and unexpected errors comes.

I strongly recommend you add the test It can be in another PR if you prefer.

**Comment by hbto** [comment]
> I strongly recommend you add the test It can be in another PR if you prefer.

@nhomar Test will be added

as suggested here:

> I lean towards there is a missing test,
> But as I said previously,
> 
> no_UnitTests_were_harmed_during_this_refactory

**Comment by nhomar** [comment]
Ok, that was not what I understand but .. Nice!

**Comment by hbto** [comment]
@nhomar 
Fixed / Done

**Comment by hbto** [comment]
@nhomar 

vauxoo_odoo-afr___build__221___coveralls_-_test_coverage_history___statistics

**Comment by hbto** [comment]
@moylop260 @nhomar 

All Functional Test for reports on Customer's instance were successful
Some bugs were discovered (old bugs) and were fixed at once in this PR.

This PR will be merged shortly

**Comment by nhomar** [comment]
I am ok with this. :+1:

**Comment by moylop260** [comment]
👍

**Comment by hbto** [comment]
@nhomar 

PR has been squashed to one commit per file modified,
waiting for test to run.

Regards

**Pull request merged**
