### PR TITLE
[REF] .travis.yml: Standardize file changing tests and adding packages.

### PR DESCRIPTION
**Pull request by KarenKawaii**

### CODE REVIEW

**Comment by yaniaular** [comment]
@KarenKawaii do you can rebase this PR?

**Comment by KarenKawaii** [comment]
Ok just let me do another commit with deleted comments.

**Comment by KarenKawaii** [comment]
@yaniaular rebase done, only is waiting for CI-Travis.

**Comment by yaniaular** [comment]
@KarenKawaii we will apply odoo-lint here? 

```
- ODOO_LINT=1
```

**Comment by KarenKawaii** [comment]
I don't put it because in previous commit there are only tests for pylint
and tests in env. May i have to add it?

**Comment by yaniaular** [comment]
@KarenKawaii sudo is false, and the tests are separated of pylint. before, odoo-lint was not. Then, we go merge this PR.  @moylop260

**Pull request merged**
